### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by AdamYLiang** [applecidera/Dreamr#1]
- [x] CSS/Styling should not be a main MVP. It will be a component of every MVP! You will be working on one MVP at a time to completion so it will have to be perfectly styled in order to continue. 

- [x] Break up Posts and Likes into two MVPs, or combine Likes with Follows, it might take more time than you think. You might want to restructure the ability to like/follow to after the dashboard is done. 

- [x] Consider adding search functionality as an MVP 

- [x] Reblogging/replies can be a bonus feature for now, these are cool features but not pivotal to the core app. 

Let me know if you have any questions or want to talk about these changes!

**Comment by applecidera** [comment]
I have adjusted the MVP list, schema, sample state, back end routes, and front end routes.
Still not very confident that I did it correctly though, let me know if things still look funky and need to be changed
